name: doctor_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3

  # retrofit is a type conversion dio client generator.
  retrofit: ^3.0.1+1
  # This package provides a library that performs static analysis of Dart code.
  analyzer: ^3.0.0
  # A powerful Http client for Dart
  dio: ^4.0.6
  # Provides Dart Build System builders for handling JSON.
  json_serializable: ^6.1.6
  # Functional programming in Dart
  dartz: ^0.10.1
  # A Pure Dart Utility library that checks for an Active Internet connection.
  internet_connection_checker: ^0.0.1+3
  # Pretty Dio logger is a Dio interceptor that logs network calls in a pretty, easy to read format.
  pretty_dio_logger: ^1.1.1
  # Offline storage for simple data
  shared_preferences: ^2.0.13
  # Code generator for data-classes/unions/pattern-matching/cloning.
  freezed: ^2.0.2
  # Service Locator for Dart and Flutter projects with some additional goodies highly inspired by Splat. (Dependency Injection)
  get_it: ^7.2.0
  # Mobile library for Android and iOS that parses Adobe After Effects animations exported as json with Bodymovin and renders them natively on mobile!
  lottie: ^1.3.0
  # A flutter package for showing a country code selector.
  country_code_picker: ^2.0.2
  # Picking images from the image library, and taking new pictures with the camera.
  image_picker: ^0.8.5+2
  # RxDart extends the capabilities of Dart Streams and StreamControllers.
  rxdart: ^0.27.3
  # A carousel slider widget.
  carousel_slider: ^4.1.1
  # Easy and Fast internationalization for your App.
  easy_localization: ^3.0.0
  # Easily restart your application from scratch, losing any previous state.
  flutter_phoenix: ^1.0.0
  # A Flutter plugin for launching a URL.
  url_launcher: ^6.1.3
  # A Flutter plugin for booking and managing an appointment.
  booking_calendar: ^1.0.2
  # A Flutter plugin to share content from your Flutter app via the platform's share dialog.
  share_plus: ^4.0.8
  # This package helps the developers to simply add their details.
  contactus: ^1.2.0
  # A Flutter widget that can be expanded or collapsed by the user.
  expandable: ^5.0.1
  # A simple yet fully customizable rating bar for flutter.
  flutter_rating_bar: ^4.0.1
  # This is a sample flutter onBoarding plugin you use to attract first-time users when they land on your App.
  onboarding: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  retrofit_generator: ^4.0.1

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/1.5x/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/4.0x/
    - assets/images/svgs/
    - assets/json/
    - assets/translations/ar-SA.json
    - assets/translations/en-US.json

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300

